// <auto-generated />
namespace myFund.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ForeightKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ForeightKey));
        
        string IMigrationMetadata.Id
        {
            get { return "201611281054145_ForeightKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
